---
title: "ds2_midterm"
author: "Ruihan Zhang"
date: "2023-03-28"
output: pdf_document
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, echo = FALSE, message = FALSE, warning = FALSE, dpi = 300, fig.width = 7)
```


```{r,include = FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(caret)
library(MASS)
library(knitr)
library(earth)
library(mgcv)
```



```{r}
set.seed(2614)
recover=load("./recovery.Rdata")
dat = dat[sample(1:10000, 2000),] %>% 
  dplyr::select(-id)
```

```{r}
#data partition
train_index=createDataPartition(dat$recovery_time, p=0.7,list = FALSE)
#training data
train_data=dat[train_index,]
x1 = model.matrix(recovery_time~., data=dat)[train_index,-1]
y1=dat$recovery_time[train_index]
#testing data
test_data=dat[-train_index,]
x2=model.matrix(recovery_time~., data=dat)[-train_index,-1]
y2=dat$recovery_time[-train_index]
```

```{r}
#exploratory analysis and data visualization
visualization = train_data %>% 
  mutate(study=case_when(
    study == "A" ~ 1,
    study == "B" ~ 2,
    study == "C" ~ 3
  ))
non_numeric= sapply(visualization, function(x) !is.numeric(x))
visualization[, non_numeric] = lapply(visualization[, non_numeric], as.numeric) 
```


```{r, warning=FALSE}

theme1 = trellis.par.get()
theme1$plot.symbol$col = rgb(.2, .4, .2, .5)
theme1$plot.symbol$pch=16
theme1$plot.line$col=rgb(.8, .1, .1, 1)
theme1$plot.line$lwd=2
theme1$strip.background$col=rgb(.0, .2, .6, .2)
trellis.par.set(theme1)

featurePlot(x = visualization[ ,1:14],
            y = visualization[ ,15],
            plot = "scatter",
            span = .5,
            labels = c("Predictors", "Recovery Time"),
            main = "Figure 1. the relationship between predictors and recovery time",
            type = c("p", "smooth"))
```

```{r}
par(mfrow=c(3,3)) 
boxplot(recovery_time~gender, data=dat, xlab="gender", ylim=c(0,150))
boxplot(recovery_time~hypertension, data=dat, xlab="hypertension", ylim=c(0,150))
boxplot(recovery_time~diabetes, data=dat, xlab="diabetes", ylim=c(0,150))
boxplot(recovery_time~vaccine, data=dat, xlab="vaccine", ylim=c(0,150))
boxplot(recovery_time~severity, data=dat, xlab="severity", ylim=c(0,150))
boxplot(recovery_time~race, data=dat, xlab="race", ylim=c(0,150))
boxplot(recovery_time~smoking, data=dat, xlab="smoking", ylim=c(0,150))

```


```{r}
#linear model
set.seed(2614)
ctrl=trainControl(method = "repeatedcv", number =10, repeats = 5)
linear = train(recovery_time ~ age + gender + race + smoking + height + 
                        weight + bmi + hypertension + diabetes + SBP + LDL + 
                        vaccine + severity + study, 
               data = train_data, 
               method = "lm", 
               trControl = ctrl)
summary(linear$finalModel)
#RMSE
test_pred1=predict(linear,newdata = test_data)
rmse1=sqrt(mean((test_pred1-test_data$recovery_time)**2))
rmse1
```

```{r}
#lasso
set.seed(2614)
lasso=train(x1,y1, 
            method = "glmnet",
                   tuneGrid = expand.grid(alpha = 1,
                                          lambda = exp(seq(-1, 5, length = 100))),
                   trControl = ctrl)
coef(lasso$finalModel, lasso$bestTune$lambda)
lasso$bestTunetest_pred2=predict(lasso,newdata=x2)
pred_lasso=predict(lasso, newx = x2, s = lasso$lambda.min)
rmse_lasso= sqrt(mean((pred_lasso-y2)**2))
rmse_lasso
coef=coef(lasso, s = lasso$lambda.min)
n.pred=sum(coef[-1] != 0)  # exclude intercept
n.pred
plot(lasso)
```


```{r}
#elastic net
set.seed(2614)
elastic_net=train(x1, y1,
                  method = "glmnet",
                  tuneGrid = expand.grid(alpha = seq(0, 1, length = 21), 
                                         lambda = exp(seq(2, -2, length = 50))),
                  trControl = ctrl)
elastic_net$bestTune
test_pred_elastic=predict(elastic_net, newdata = x2)
rmse_elastic=sqrt(mean((test_pred_elastic - test_data$recovery_time)**2))
rmse_elastic
plot(elastic_net)
```





```{r}
#pls
set.seed(2614)
pls=train(x1, y1,
          method = "pls",
          tuneGrid = data.frame(ncomp = 1:15), # CHECK THIS
          trControl = ctrl,
          preProcess = c("center", "scale"))

summary(pls$finalModel)
test_pred_pls=predict(pls, newdata = x2)
rmse_pls=sqrt(mean((test_pred_pls - test_data$recovery_time)**2))
rmse_pls
plot(pls)
```

```{r}
#mars
set.seed(2614)
mars_grid = expand.grid(degree = 1:3, 
                        nprune = 2:17) 
mars = train(x1, y1,
             method = "earth",
             tuneGrid = mars_grid,
             trControl = ctrl)
kable(mars$bestTune,"simple")
coef(mars$finalModel)
test_pred_mars=predict(mars, newdata = x2)
rmse_mars=sqrt(mean((test_pred_mars - test_data$recovery_time)**2))
rmse_mars
summary(mars)
plot(mars)
```



```{r}
#gam with all predictors
gam = train(x1, y1,
                 method = "gam",
                 trControl = ctrl,
                 control = gam.control(maxit = 200))
summary(gam$finalModel)
gam$df.residual
test_pred_gam=predict(gam, newdata = x2)
rmse_gam=sqrt(mean((test_pred_gam-test_data$recovery_time)**2))
rmse_gam
plot(gam)
```


```{r}
#model comparison
set.seed(2614)
res=resamples(list(lm = linear,lasso = lasso, elastic_net = elastic_net,pls = pls,gam=gam,mars = mars))
summary(res)
```


```{r}
bwplot(res, 
       metric = "RMSE",
       main = "Figure 2. Model Comparison")
```

```{r}
#training rmse
model_performance=gam$results$RMSE
model_performance
#testing rmse
rmse_gam
```

```{r}
set.seed(2614)
final_model = gam(recovery_time ~ gender + race + + smoking + 
                         hypertension + diabetes + vaccine + severity + study + 
                         s(age) + s(SBP) + s(LDL) + s(bmi) + s(height) + 
                         s(weight), 
              data = train_data) 
summary(final_model)
par(mfrow=c(2,3)) 

plot(final_model)
```



